### ISSUE TITLE
is forcats-py too close to the R package repo's name?

### ISSUE THREAD

**Issue by machow** [machow/catfact#1]
@hadley I just re-read the [yhat/ggplot issue](https://github.com/yhat/ggpy/issues/537) on package names, and want to make sure I get the naming on a "forcats for python" port right.

**What will it be?**

A port of forcats that works on pandas Series. Right now it lives in [siuba.dply.forcats](https://github.com/machow/siuba/blob/master/siuba/dply/forcats.py). I'm largely aiming for knowledge transfer between R <-> python for users, and experimenting with converting code between the two user interfaces using static analysis (via a package called [wrestlr](https://github.com/machow/wrestlr)).

**Naming**

* Does a repo named `forcats-py` work for you?
* What about if it uses `pip install forcats`?

(definitely happy to figure out better names)

Thanks!

**Comment by hadley** [comment]
I don't have any strong feelings about the repo name, but I think if the python library is called `forcats`, it's a bit too close to original (so that it's likely to cause confusion).

**Comment by hadley** [comment]
You could call it forsnakes 🤣

**Comment by machow** [comment]
Ah, I forgot to say--thanks for your feedback! I went into a deep name ponder 😅, but finally renamed to catfact.

When users `pip install forcats`, I'll have it tell them to install catfact instead!

**Comment by hadley** [comment]
I love catfact 🤣
